name: Validate data with schema

on:
    push:

env:
  SCHEMA_PATH: schema.json # set this to the JSON Schema path
  SAMPLE_PATH: valid-sample.geojson # set this to the sample file path

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # AJV does not consider the geojson external schema, but the errors are more detailed
            # so I put both validator,
            - name: Validate JSON with AVJ.
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: ${{ env.SCHEMA_PATH }}
                  INPUT_JSONS: ${{ env.SAMPLE_PATH }}

            # Install a python cli checker, `jsonschema` that have poor errors but can check that the example is a valid geojson
            # (unlike ajv it resolves the external geojson schema)
            - name: Installation Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: "3.7"
            - name: Cache pip
              uses: actions/cache@v1
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-
            - name: Installation des dépendances
              run: pip install jsonschema
            - name: Vérification du schéma et des fichiers d'exemples
              run: |
                  jsonschema --instance ${{ env.SAMPLE_PATH }} ${{ env.SCHEMA_PATH }}
